#!name=日常任务
#!desc=日常任务信息获取，此模块无需关闭
#!author=bautistaclay
#!category= ⚙️ ▸ 日常任务

[Script]
# > 🥳脚本功能: 获取哔哩哔哩日常任务脚本需要的各项参数
B站Cookie(APP) = type=http-request,pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/fingerprint\?,script-path=https://raw.githubusercontent.com/ClydeTime/BiliBili/main/js/BiliBiliDailyBonus.js,requires-body=0
B站Cookie(网页) = type=http-request,pattern=^https?:\/\/m\.bilibili\.com/$,script-path=https://raw.githubusercontent.com/ClydeTime/BiliBili/main/js/BiliBiliDailyBonus.js,requires-body=0
# > 🥳脚本功能: 获取自动加入TestFlight需要的各项参数
自动获取TestFlight的Appid = type=http-request, pattern=^https:\/\/testflight\.apple\.com\/v3\/accounts\/.*\/ru\/([^\/]+)(?!\/accept)$, script-path=https://raw.githubusercontent.com/MCdasheng/QuantumultX/main/Scripts/myScripts/TF_appIds.js, timeout=60

[MITM]
hostname = %APPEND% app.bilibili.com, m.bilibili.com,testflight.apple.com