#!name=爱阅书香
#!desc=爱阅书香会员激励
#!author=Mattraks
#!icon=https://raw.githubusercontent.com/bautistaclay/ios/master/IconSet/App/iFreeTime04.png
#!category=⚙️ ▸ 功能增强

[Script]
爱阅书香会员激励 = type=http-response, pattern=^https:\/\/api-access\.pangolin-sdk-toutiao\.com\/api\/ad\/union\/sdk\/get_ads.+, script-path=https://raw.githubusercontent.com/bautistaclay/ios/master/Scripts/iFreeTime.js, requires-body=true, max-size=0, script-update-interval=0, timeout=10

[MITM]
hostname = %APPEND% api-access.pangolin-sdk-toutiao.com