#!name=爱阅书香
#!desc=爱阅书香会员激励
#!author=Mattraks
#!icon=https://raw.githubusercontent.com/bautistaclay/ios/master/IconSet/App/iFreeTime04.png
#!category=⚙️ ▸ 应用增强

[Rule]
DOMAIN,api-access.pangolin-sdk-toutiao.com,DIRECT
DOMAIN,open.e.kuaishou.com,REJECT
DOMAIN,video-dsp.pddpic.com,REJECT
DOMAIN,log-api.pangolin-sdk-toutiao.com,REJECT
DOMAIN,log-api.pangolin-sdk-toutiao-b.com,REJECT
DOMAIN,ether-pack.pangolin-sdk-toutiao.com,REJECT
DOMAIN,mssdk-bu.bytedance.com,REJECT
DOMAIN,images.pinduoduo.com,REJECT
DOMAIN,ic.snssdk.com,REJECT
DOMAIN,log.snssdk.com,REJECT
DOMAIN,log-hl.snssdk.com,REJECT
DOMAIN,tnc3-aliec2.snssdk.com,REJECT
DOMAIN-SUFFIX,gdt.qq.com,REJECT
DOMAIN-SUFFIX,app-measurement.com,REJECT
DOMAIN-SUFFIX,umeng.com,REJECT
DOMAIN-SUFFIX,umengcloud.com,REJECT
DOMAIN-SUFFIX,pglstatp-toutiao.com,REJECT
DOMAIN-SUFFIX,ctobsnssdk.com,REJECT
DOMAIN-SUFFIX,ugdtimg.com,REJECT
DOMAIN-SUFFIX,doubleclick.net,REJECT

[Script]
爱阅书香 = type=http-response, pattern=^https:\/\/api-access\.pangolin-sdk-toutiao\.com\/api\/ad\/union\/sdk\/get_ads.+, script-path=https://raw.githubusercontent.com/bautistaclay/ios/master/Scripts/iFreeTime.js, requires-body=true, max-size=0, script-update-interval=0, timeout=10

[MITM]
hostname = %APPEND% api-access.pangolin-sdk-toutiao.com